<?php

declare(strict_types=1);

return [

    /*
    |--------------------------------------------------------------------------
    | Company Information
    |--------------------------------------------------------------------------
    |
    | This information will appear on all invoices generated by the system.
    |
    */

    'company' => [
        'name' => env('INVOICE_COMPANY_NAME', 'My8K IPTV'),
        'address' => env('INVOICE_COMPANY_ADDRESS', ''),
        'city' => env('INVOICE_COMPANY_CITY', ''),
        'country' => env('INVOICE_COMPANY_COUNTRY', ''),
        'phone' => env('INVOICE_COMPANY_PHONE', ''),
        'email' => env('INVOICE_COMPANY_EMAIL', ''),
        'website' => env('INVOICE_COMPANY_WEBSITE', ''),
        'vat_number' => env('INVOICE_COMPANY_VAT', ''),
    ],

    /*
    |--------------------------------------------------------------------------
    | Default Settings
    |--------------------------------------------------------------------------
    |
    | Default tax rate and currency for invoices.
    |
    */

    'defaults' => [
        'tax_rate' => (float) env('INVOICE_TAX_RATE', 0),
        'currency' => env('INVOICE_DEFAULT_CURRENCY', 'USD'),
    ],

    /*
    |--------------------------------------------------------------------------
    | Storage Settings
    |--------------------------------------------------------------------------
    |
    | Configure where invoice PDFs are stored.
    |
    */

    'storage' => [
        'disk' => env('INVOICE_STORAGE_DISK', 'local'),
        'path' => env('INVOICE_STORAGE_PATH', 'invoices'),
    ],

];
